server:
  port: 8199
  servlet:
    context-path: /equipmettory
  compression:
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml, image/png, image/jpg, image/gif, image/jpeg
# http://localhost:8199/equipmettory/swagger-ui/4.15.5/index.html
# ??? ????????
app:
  equipment:
    url: localhost:8190/equipment-service
    name: equipment-service
    health: health
  location:
    url: localhost:8191/location-service
    name: location-service
    health: health